### PR TITLE
Test: Inverter log

### PR DESCRIPTION
**Pull request by tkdgusqkr**
Programmer: 박상현
Modifying code:
AMKInverter.c
AMKInverter.h
SchedulerTask.c
SchedulerTask_Cpu2.c

### CODE REVIEW

**Comment by tkdgusqkr** [comment]
Programmer: 박상현
Modifying code:
AMKInverter.c

**Comment by tkdgusqkr** [comment]
Programmer: 박상현
Modifying code:
AMKInverter.c
Issue:
Modify CAN msg ID (Standard -> Extended)

**Comment by tkdgusqkr** [comment]
Programmer: 박상현
Modifying code:
ShockValue.c
ShockValue.h
SchedulerTask.c
Issue:
Make Shock log

**Comment by InitusNovus** [comment]
코드 올려본 거?

**Pull request merged**
